import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TopStarRepos from './top-star-repos'
import executeQuery from '../lib/tidb'

export default function Home({ rows }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>OSS Insight Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://ossinsight.io/">OSS Insight</a>
        </h1>

        <TopStarRepos rows={rows} />

      </main>
    </div>
  )
}

export async function getStaticProps() {
  const results = await executeQuery(`
    SELECT repo_name, count(*) AS events_count
      FROM github_events
      WHERE type = 'WatchEvent'
      GROUP BY 1
      ORDER BY 2 DESC
      LIMIT 20;
  `);

  let rows = [];
  for (const row of results) {
    rows.push({
      repo_name: row.repo_name,
      events_count: row.events_count
    });
  }

  return {
    props: {
      rows,
    }
  }
}